remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme
title: "Carlos Chaves – Head of QA"
subtitle: "Building quality culture through automation, strategy, and continuous learning"
avatar: /logo.png
linkedin: http://www.linkedin.com/in/carlos-chaves-3b616924
social:
  name: Carlos Chaves
  links:
    - http://www.linkedin.com/in/carlos-chaves-3b616924
    - https://github.com/cchaves21
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
