name: Trigger Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PLAYWRIGHT_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/cchaves21/Playwright-site-checker/dispatches \
            -d '{"event_type":"run-playwright-tests"}'