name: Trigger Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Repository Tests
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PLAYWRIGHT_TRIGGER_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/cchaves21/Playwright-site-checker/dispatches \
            -d '{"event_type":"run-playwright-tests","client_payload":{"repository":"${{ github.repository }}","ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'

      - name: Check API Response
        if: failure()
        run: |
          echo "Failed to trigger Playwright tests. Check token permissions and repository settings."